### PR TITLE
Added option to run activity for each tests method. 

### PR DESCRIPTION
**Pull request by dbacinski**
Added option to run activity for each tests method. It is needed for UI tests (Espresso).

Change is backward compatible.

### CODE REVIEW

**Comment by AndrewReitz** [comment]
Could you document the enum RunMode, and what SPECIFICATION and METHOD do?

I'm working on updating snap so the tests can run.

**Comment by AndrewReitz** [comment]
I'm seeing "java.lang.IllegalStateException: failed to find target android-22" could this be with the update to the build tools? I have android-22 installed. I'm thinking maybe we should bump the compileSdkVersion to 23?

**Comment by dbacinski** [comment]
I will do documentation for this change.

Previous builds also failed with the same error, so this is not problem with build tools version. 
More likely sdk v22 is missing on build agent. I do not know how fix, I have never build project on Snap CI.

**Comment by dbacinski** [comment]
Documentation added.

**Comment by dbacinski** [comment]
Regarding failed build check this link:
https://docs.snap-ci.com/the-ci-environment/languages/android/

You should execute this to download sdk 22:
$ echo y | android update sdk --no-ui --filter android-22

**Comment by dbacinski** [comment]
Example shell scripts:
https://github.com/snap-ci-examples/android-emulator

**Comment by AndrewReitz** [comment]
I have `echo y | android update sdk --no-ui --filter android-22` in the setup. Not sure what changed. I'm going to try and updated everything to 23 today see if that will flush out some of the problems.

**Comment by AndrewReitz** [comment]
Thanks for this addition!

**Comment by AndrewReitz** [comment]
@dbacinski Just released to bintray/artifactory and central as 1.2.2. Still can't figure out what's wrong with circle...

**Pull request merged**
